export interface Hero {
  id: number;
  name: string;
  kana: string;
  role: string;
  role2: string;
  election: string;
  license: string;
  newcomer: string;
  kokujibi: Date;
  tohyobi: Date;
  belongs: string;
  almaMater: string;
  almaMater2: string;
  district: string;
  continuecount: number;
  count: number;
  twitter: string;
  wikipedia: string;
  birthday: Date;
  candidate: boolean;
  candidateType: string;
  candidatePrefecture: string;
  candidatedistrict: string;
  image: string;
  hp: string;
  url: string;
  detail: string;
}
